development:
  # The base URL on which you want to install Juvia, without trailing slash.
  base_url: http://juvia.local
  from: comment-bot@truffles.me.uk

production:
  base_url: http://juvia.yoursite.com
  from: comment-bot@truffles.me.uk
